<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>practical1_task2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="practical1_task2_3_files/libs/clipboard/clipboard.min.js"></script>
<script src="practical1_task2_3_files/libs/quarto-html/quarto.js"></script>
<script src="practical1_task2_3_files/libs/quarto-html/popper.min.js"></script>
<script src="practical1_task2_3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="practical1_task2_3_files/libs/quarto-html/anchor.min.js"></script>
<link href="practical1_task2_3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="practical1_task2_3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="practical1_task2_3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="practical1_task2_3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="practical1_task2_3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">practical1_task2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("naniar")</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("mice")</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'mice'

The following object is masked from 'package:stats':

    filter

The following objects are masked from 'package:base':

    cbind, rbind</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape2'

The following object is masked from 'package:tidyr':

    smiths</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("survival")</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Type 'citation("pROC")' for a citation.

Attaching package: 'pROC'

The following objects are masked from 'package:stats':

    cov, smooth, var</code></pre>
</div>
</div>
<section id="data-manipulation" class="level2">
<h2 class="anchored" data-anchor-id="data-manipulation">Data Manipulation</h2>
<section id="data-importation" class="level3">
<h3 class="anchored" data-anchor-id="data-importation">Data Importation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/theodruilhe/Documents/M2_D3S/scoring_project"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Import X</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(<span class="st">"data"</span>, <span class="st">"our_data"</span>, <span class="st">"X.rds"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">file.exists</span>(file_path)) {</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(file_path)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"File not found. Please check the file path."</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co"># import target_Y</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(<span class="st">"data"</span>, <span class="st">"our_data"</span>, <span class="st">"target_Y.rds"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">file.exists</span>(file_path)) {</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(file_path)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"File not found. Please check the file path."</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Create an new ID for the join</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> X <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ID =</span> <span class="fu">paste</span>(gvkey, fyear, <span class="at">sep =</span> <span class="st">"_"</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> y <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ID =</span> <span class="fu">paste</span>(gvkey, fyear, <span class="at">sep =</span> <span class="st">"_"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-quality-check" class="level3">
<h3 class="anchored" data-anchor-id="data-quality-check">Data Quality check</h3>
<p>Function to calculate the number of duplicates</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>count_duplicates <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Total number of rows in the dataset</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  number_of_rows <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Number of distinct IDs</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  distinct_count <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">total_distinct_IDs =</span> <span class="fu">n_distinct</span>(ID)) <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(total_distinct_IDs) <span class="co"># Extract the numeric value</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate and return the number of duplicates</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  number_of_duplicates <span class="ot">&lt;-</span> number_of_rows <span class="sc">-</span> distinct_count</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(number_of_duplicates)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="duplicates-in-x" class="level4">
<h4 class="anchored" data-anchor-id="duplicates-in-x">Duplicates in X</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>duplicates_count_X <span class="ot">&lt;-</span> <span class="fu">count_duplicates</span>(X)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicates_count_X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 46</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>duplicates_X <span class="ot">&lt;-</span> X <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ID) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicates_X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 92 × 20
   fyear gvkey       ROA      ROE net_profit_margin asset_turnover
   &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt;
 1  2010 028543 -0.00430 -0.00907          -0.00244          1.76 
 2  2010 002176  0.0348   0.0824            0.0960           0.363
 3  2010 020217  0.192   -4.46              0.549            0.350
 4  2010 002176  0.0348   0.0824            0.0960           0.363
 5  2010 028543 -0.00430 -0.00907          -0.00244          1.76 
 6  2010 020217  0.192   -4.46              0.549            0.350
 7  2011 017266 -0.0180  -0.0437           -0.0188           0.956
 8  2011 032280  0.105    0.154             0.269            0.392
 9  2011 183812 NA       NA                NA               NA    
10  2011 017266 -0.0180  -0.0437           -0.0188           0.956
# ℹ 82 more rows
# ℹ 14 more variables: inventory_turnover &lt;dbl&gt;, debt_to_equity &lt;dbl&gt;,
#   debt_ratio &lt;dbl&gt;, PE_ratio &lt;dbl&gt;, market_to_book &lt;dbl&gt;,
#   operating_cash_flow_to_debt &lt;dbl&gt;, free_cash_flow_to_sales &lt;dbl&gt;,
#   book_value &lt;dbl&gt;, ebitda &lt;dbl&gt;, ebitda_margin &lt;dbl&gt;, roic &lt;dbl&gt;,
#   leverage &lt;dbl&gt;, interest_coverage &lt;dbl&gt;, ID &lt;chr&gt;</code></pre>
</div>
</div>
<p>For the duplicates rows the values of the columns are the same but not for not for the “PE_ratio” and “market_to_book” thus we will investigate the computation this columns.</p>
<p>We choose to keep only the smallest value for theses variables in case of duplicates</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> X <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ID) <span class="sc">%&gt;%</span> <span class="co"># Group by ID to handle duplicates</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(PE_ratio, market_to_book) <span class="sc">%&gt;%</span> <span class="co"># Sort by smallest PE_ratio and market_to_book</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="co"># Keep only the first row (smallest values)</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="co"># Remove grouping</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We check for other duplicates</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>duplicates_count_X <span class="ot">&lt;-</span> <span class="fu">count_duplicates</span>(X)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicates_count_X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="duplicates-in-y" class="level4">
<h4 class="anchored" data-anchor-id="duplicates-in-y">Duplicates in Y</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>duplicates_count_y <span class="ot">&lt;-</span> <span class="fu">count_duplicates</span>(y)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicates_count_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 680</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>duplicates_y <span class="ot">&lt;-</span> y <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ID) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicates_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 957 × 4
# Groups:   ID [277]
   gvkey  fyear     Y ID         
   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      
 1 006307  2010     0 006307_2010
 2 006307  2010     0 006307_2010
 3 006307  2010     0 006307_2010
 4 006307  2010     0 006307_2010
 5 006307  2011     0 006307_2011
 6 006307  2011     0 006307_2011
 7 006307  2011     0 006307_2011
 8 006307  2011     0 006307_2011
 9 006307  2012     0 006307_2012
10 006307  2012     0 006307_2012
# ℹ 947 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> y <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>duplicates_count_y <span class="ot">&lt;-</span> <span class="fu">count_duplicates</span>(y)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicates_count_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>duplicates_y <span class="ot">&lt;-</span> y <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ID) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>() <span class="sc">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicates_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
# Groups:   ID [4]
  gvkey  fyear     Y ID         
  &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      
1 008387  2015     0 008387_2015
2 008387  2015     1 008387_2015
3 164607  2015     0 164607_2015
4 164607  2015     1 164607_2015
5 178266  2014     0 178266_2014
6 178266  2014     1 178266_2014
7 184006  2015     0 184006_2015
8 184006  2015     1 184006_2015</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the distinct IDs from duplicates_y</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>distinct_ids <span class="ot">&lt;-</span> duplicates_y <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(ID) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(ID) <span class="co"># Extract as a vector</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co"># View the distinct IDs</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(distinct_ids)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "008387_2015" "164607_2015" "178266_2014" "184006_2015"</code></pre>
</div>
</div>
<p>We decide to keep only the rows with Y = 1</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the original dataset to remove rows where Y = 0 for the distinct IDs</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> y <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(ID <span class="sc">%in%</span> distinct_ids <span class="sc">&amp;</span> Y <span class="sc">==</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>duplicates_count_y <span class="ot">&lt;-</span> <span class="fu">count_duplicates</span>(y)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicates_count_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
</section>
<section id="create-final-data" class="level3">
<h3 class="anchored" data-anchor-id="create-final-data">Create final Data</h3>
<p>Join the data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform the inner join</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> y <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(X, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"ID"</span> <span class="ot">=</span> <span class="st">"ID"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Delete the useless columns</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>fyear.y, <span class="sc">-</span>gvkey.y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename gvkey and fyear</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)[<span class="fu">colnames</span>(data) <span class="sc">==</span> <span class="st">"gvkey.x"</span>] <span class="ot">&lt;-</span> <span class="st">"gvkey"</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)[<span class="fu">colnames</span>(data) <span class="sc">==</span> <span class="st">"fyear.x"</span>] <span class="ot">&lt;-</span> <span class="st">"fyear"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform Y as a binary variable</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Y =</span> <span class="fu">ifelse</span>(Y <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="check-for-duplicates" class="level4">
<h4 class="anchored" data-anchor-id="check-for-duplicates">Check for duplicates</h4>
<p>First we will check if we do not have duplicates in the ID column</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>duplicates_count_data <span class="ot">&lt;-</span> <span class="fu">count_duplicates</span>(data)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicates_count_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="missing-values-processing" class="level2">
<h2 class="anchored" data-anchor-id="missing-values-processing">Missing Values Processing</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get info about the data</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [44,915 × 21] (S3: tbl_df/tbl/data.frame)
 $ gvkey                      : chr [1:44915] "001004" "001004" "001004" "001004" ...
 $ fyear                      : int [1:44915] 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 ...
 $ Y                          : num [1:44915] 0 0 0 0 0 0 0 0 0 0 ...
 $ ID                         : chr [1:44915] "001004_2010" "001004_2011" "001004_2012" "001004_2013" ...
 $ ROA                        : num [1:44915] 0.04098 0.03084 0.02574 0.03314 0.00673 ...
 $ ROE                        : num [1:44915] 0.0835 0.0783 0.0599 0.0729 0.0121 ...
 $ net_profit_margin          : num [1:44915] 0.0393 0.0326 0.0254 0.0358 0.0064 ...
 $ asset_turnover             : num [1:44915] 1.042 0.945 1.014 0.925 1.052 ...
 $ inventory_turnover         : num [1:44915] 2.78 2.77 2.94 2.5 2.37 ...
 $ debt_to_equity             : num [1:44915] 1.039 1.538 1.325 1.199 0.793 ...
 $ debt_ratio                 : num [1:44915] 0.51 0.606 0.57 0.545 0.442 ...
 $ PE_ratio                   : num [1:44915] 12.3 14.3 11.8 12.6 92.7 ...
 $ market_to_book             : num [1:44915] 1.03 1.118 0.704 0.92 1.119 ...
 $ operating_cash_flow_to_debt: num [1:44915] 0.125 0.0709 0.1338 0.1166 -0.0642 ...
 $ free_cash_flow_to_sales    : num [1:44915] -0.00917 0.00145 0.05782 0.05568 -0.05601 ...
 $ book_value                 : num [1:44915] 770 1215 1080 1038 565 ...
 $ ebitda                     : num [1:44915] 196.3 222.7 245.2 256 83.7 ...
 $ ebitda_margin              : num [1:44915] 0.1105 0.1073 0.1131 0.1258 0.0525 ...
 $ roic                       : num [1:44915] 0.1534 0.1344 0.1507 0.1567 0.0838 ...
 $ leverage                   : num [1:44915] 0.347 0.478 0.435 0.388 0.154 ...
 $ interest_coverage          : num [1:44915] 6.4 5.9 5.89 6.1 3.16 ...</code></pre>
</div>
</div>
<p>We adopt Shumway’s approach to handle extreme values, ensuring the data remains robust and well-distributed. Specifically:</p>
<ol type="1">
<li>Values exceeding the 99th percentile of each variable are capped at the 99th percentile value.</li>
<li>Values falling below the 1st percentile of each variable are floored at the 1st percentile value.</li>
</ol>
<p>This technique effectively minimizes the impact of outliers while preserving the integrity of the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to truncate values at 1st and 99th percentiles</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>truncate_outliers <span class="ot">&lt;-</span> <span class="cf">function</span>(column) {</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  p1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(column, <span class="fl">0.01</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)  <span class="co"># 1st percentile</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  p99 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(column, <span class="fl">0.99</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># 99th percentile</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  column <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(column <span class="sc">&lt;</span> p1, p1, column)   <span class="co"># Floor at 1st percentile</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  column <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(column <span class="sc">&gt;</span> p99, p99, column) <span class="co"># Cap at 99th percentile</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(column)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply truncation to all numeric columns except Y</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">all_of</span>(<span class="st">"Y"</span>), truncate_outliers))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values and give the proportion of missing values by column</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)) <span class="sc">/</span> <span class="fu">n</span>())) <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>() <span class="sc">%&gt;%</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(value))</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print missing values</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 2
   key                           value
   &lt;chr&gt;                         &lt;dbl&gt;
 1 inventory_turnover          0.308  
 2 interest_coverage           0.282  
 3 book_value                  0.0569 
 4 ebitda_margin               0.0516 
 5 free_cash_flow_to_sales     0.0514 
 6 net_profit_margin           0.0492 
 7 roic                        0.0103 
 8 operating_cash_flow_to_debt 0.00608
 9 leverage                    0.00608
10 ebitda                      0.00599
# ℹ 11 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(data)  <span class="co"># Plot missing values by variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practical1_task2_3_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We identified three groups of variables based on their proportion of missing values:</p>
<ol type="1">
<li><strong>High Missingness (&gt;30%)</strong>:
<ul>
<li>Variables: <code>inventory_turnover</code> and <code>interest_coverage</code>.</li>
<li>Action: These variables have over 30% missing values and will be removed from the dataset due to their unreliability.</li>
</ul></li>
<li><strong>Moderate Missingness (~5%)</strong>:
<ul>
<li>Variables: <code>book_value</code>, <code>ebitda_margin</code>, <code>free_cash_flow_to_sales</code>, and <code>net_profit_margin</code>.</li>
<li>Action: These variables will be handled individually on a case-by-case basis to ensure the most appropriate imputation or processing.</li>
</ul></li>
<li><strong>Low Missingness (&lt;1%)</strong>:
<ul>
<li>Variables: Remaining variables with less than 1% missingness.</li>
<li>Action: Mean imputation will be applied to fill the missing values for these variables, ensuring minimal impact on the dataset’s integrity.</li>
</ul></li>
</ol>
<section id="high-missingness" class="level4">
<h4 class="anchored" data-anchor-id="high-missingness">1. High missingness</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>inventory_turnover, <span class="sc">-</span>interest_coverage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="distribution-of-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="distribution-of-missing-values">Distribution of missing values</h4>
<p>We want to know in which case we are based on these kind of distributions:</p>
<p><strong>a. Univariate Missing Values:</strong> If the same individuals have missing values for the same (d &lt; p) variables.</p>
<p><strong>b. Monotonic Missing Values:</strong> If the variables can be ordered so that, when the observation (y_{ij}) is missing for the variable (Y_j), then all the following variables for the same individual, (y_{ik}, k &gt; j), are also missing.</p>
<p><strong>c.&nbsp;Non-Monotonic or Arbitrary Missing Values:</strong> If the missing values are without structure, i.e., they are distributed without particular structure in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un dataset avec les lignes ayant au moins une valeur manquante</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>rows_with_na <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_any</span>(<span class="fu">everything</span>(), is.na))</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le nouveau dataset</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(rows_with_na)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,021 × 19
   gvkey  fyear     Y ID             ROA    ROE net_profit_margin asset_turnover
   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt;
 1 001234  2020     0 001234_20… 0.120   0.134             0.218           0.553
 2 001234  2021     0 001234_20… 0.124   0.135             0.200           0.617
 3 001234  2022     0 001234_20… 0.132   0.146             0.191           0.693
 4 001234  2023     0 001234_20… 0.0744  0.0799            0.115           0.649
 5 001239  2010     0 001239_20… 0.0827  0.117             0.0972          0.851
 6 001274  2017     0 001274_20… 0.00355 0.0106            0.0140          0.253
 7 001327  2010     0 001327_20… 0.0878  0.104             0.128           0.685
 8 001327  2011     0 001327_20… 0.120   0.141             0.160           0.751
 9 001327  2012     0 001327_20… 0.0946  0.106             0.129           0.734
10 001327  2013     0 001327_20… 0.119   0.132             0.155           0.768
# ℹ 5,011 more rows
# ℹ 11 more variables: debt_to_equity &lt;dbl&gt;, debt_ratio &lt;dbl&gt;, PE_ratio &lt;dbl&gt;,
#   market_to_book &lt;dbl&gt;, operating_cash_flow_to_debt &lt;dbl&gt;,
#   free_cash_flow_to_sales &lt;dbl&gt;, book_value &lt;dbl&gt;, ebitda &lt;dbl&gt;,
#   ebitda_margin &lt;dbl&gt;, roic &lt;dbl&gt;, leverage &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compter le nombre distinct de colonnes avec des valeurs manquantes par gvkey</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>missing_values_per_gvkey <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gvkey) <span class="sc">%&gt;%</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">distinct_missing_columns =</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), is.na), any))</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>missing_distribution <span class="ot">&lt;-</span> missing_values_per_gvkey <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(distinct_missing_columns) <span class="sc">%&gt;%</span> <span class="co"># Grouper par nombre de colonnes avec NA</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">count_gvkey =</span> <span class="fu">n</span>() <span class="co"># Compter le nombre de gvkey pour chaque groupe</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(distinct_missing_columns) <span class="co"># Trier par nombre de colonnes avec NA</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les résultats</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_distribution)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
   distinct_missing_columns count_gvkey
                      &lt;int&gt;       &lt;int&gt;
 1                        0        4380
 2                        1         676
 3                        2          63
 4                        3         696
 5                        4          30
 6                        5          41
 7                        6          16
 8                        8           5
 9                        9           4
10                       10          52
11                       11           3
12                       13           1
13                       15          73</code></pre>
</div>
</div>
<p>For the company where the number of distinct columns with missing values is greater than 5 we will delete them</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Supprimer les gvkey avec au moins 5 distinct_missing_columns</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(missing_values_per_gvkey, <span class="at">by =</span> <span class="st">"gvkey"</span>) <span class="sc">%&gt;%</span> <span class="co"># Joindre avec les informations des colonnes manquantes</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(distinct_missing_columns <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">|</span> <span class="fu">is.na</span>(distinct_missing_columns)) <span class="sc">%&gt;%</span> <span class="co"># Garder les gvkey avec moins de 5 colonnes manquantes</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>distinct_missing_columns) <span class="co"># Optionnel : Supprimer la colonne supplémentaire si elle n'est plus nécessaire</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le dataset filtré</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 43,919 × 19
   gvkey  fyear     Y ID            ROA     ROE net_profit_margin asset_turnover
   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt;
 1 001004  2010     0 001004_2… 0.0410  0.0835            0.0393           1.04 
 2 001004  2011     0 001004_2… 0.0308  0.0783            0.0326           0.945
 3 001004  2012     0 001004_2… 0.0257  0.0599            0.0254           1.01 
 4 001004  2013     0 001004_2… 0.0331  0.0729            0.0358           0.925
 5 001004  2014     0 001004_2… 0.00673 0.0121            0.00640          1.05 
 6 001004  2015     0 001004_2… 0.0331  0.0551            0.0287           1.15 
 7 001004  2016     0 001004_2… 0.0376  0.0618            0.0320           1.18 
 8 001004  2017     0 001004_2… 0.0102  0.0167            0.00892          1.15 
 9 001004  2018     0 001004_2… 0.00494 0.00828           0.00366          1.35 
10 001004  2019     0 001004_2… 0.00212 0.00487           0.00211          1.00 
# ℹ 43,909 more rows
# ℹ 11 more variables: debt_to_equity &lt;dbl&gt;, debt_ratio &lt;dbl&gt;, PE_ratio &lt;dbl&gt;,
#   market_to_book &lt;dbl&gt;, operating_cash_flow_to_debt &lt;dbl&gt;,
#   free_cash_flow_to_sales &lt;dbl&gt;, book_value &lt;dbl&gt;, ebitda &lt;dbl&gt;,
#   ebitda_margin &lt;dbl&gt;, roic &lt;dbl&gt;, leverage &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We will look at the remaining missing values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values and give the proportion of missing values by column</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)) <span class="sc">/</span> <span class="fu">n</span>())) <span class="sc">%&gt;%</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>() <span class="sc">%&gt;%</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(value))</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print missing values</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19 × 2
   key                            value
   &lt;chr&gt;                          &lt;dbl&gt;
 1 book_value                  0.0544  
 2 ebitda_margin               0.0464  
 3 free_cash_flow_to_sales     0.0461  
 4 net_profit_margin           0.0441  
 5 roic                        0.00392 
 6 ebitda                      0.00232 
 7 leverage                    0.00159 
 8 market_to_book              0.000774
 9 PE_ratio                    0.000638
10 operating_cash_flow_to_debt 0.000478
11 ROE                         0.000250
12 debt_to_equity              0.000250
13 gvkey                       0       
14 fyear                       0       
15 Y                           0       
16 ID                          0       
17 ROA                         0       
18 asset_turnover              0       
19 debt_ratio                  0       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(data)  <span class="co"># Plot missing values by variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practical1_task2_3_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="moderate-missingness" class="level4">
<h4 class="anchored" data-anchor-id="moderate-missingness">2. Moderate Missingness</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>book_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
  -13.32    53.61   456.88  3949.04  2228.48 93472.65     2391 </code></pre>
</div>
</div>
<p>Feature correlation analysis to asses the relevance of imputation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>numeric_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">where</span>(is.numeric))</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>correlations <span class="ot">&lt;-</span> numeric_data <span class="sc">%&gt;%</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">cor</span>(.x, numeric_data<span class="sc">$</span>book_value, <span class="at">use =</span> <span class="st">"complete.obs"</span>)))</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>correlation_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">variable =</span> <span class="fu">colnames</span>(numeric_data), <span class="at">correlation =</span> <span class="fu">as.numeric</span>(correlations))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Heatmap</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(numeric_data, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformer la matrice en un format long pour ggplot</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>melted_correlation <span class="ot">&lt;-</span> <span class="fu">melt</span>(correlation_matrix)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Heatmap des corrélations</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(melted_correlation, <span class="fu">aes</span>(<span class="at">x =</span> Var1, <span class="at">y =</span> Var2, <span class="at">fill =</span> value)) <span class="sc">+</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="at">low =</span> <span class="st">"blue"</span>, <span class="at">high =</span> <span class="st">"red"</span>, <span class="at">mid =</span> <span class="st">"white"</span>, <span class="at">midpoint =</span> <span class="dv">0</span>, <span class="at">limit =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Correlation Heatmap"</span>, <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practical1_task2_3_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>correlation_with_book_value <span class="ot">&lt;-</span> correlation_df <span class="sc">%&gt;%</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(variable <span class="sc">!=</span> <span class="st">"book_value"</span>) <span class="co"># Exclure la corrélation avec elle-même</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(correlation_with_book_value, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(variable, correlation), <span class="at">y =</span> correlation)) <span class="sc">+</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Correlation with Book Value"</span>, <span class="at">x =</span> <span class="st">"Variables"</span>, <span class="at">y =</span> <span class="st">"Correlation"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practical1_task2_3_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that ebitda and book value are higly correlated, we can think of use ebitda to impute missing values in book_value</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrer les lignes où book_value est NA</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>rows_with_na_book_value <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(book_value))</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher le dataset résultant</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(rows_with_na_book_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,391 × 19
   gvkey  fyear     Y ID              ROA   ROE net_profit_margin asset_turnover
   &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt;
 1 001239  2010     0 001239_2010 0.0827  0.117           0.0972           0.851
 2 001327  2010     0 001327_2010 0.0878  0.104           0.128            0.685
 3 001327  2011     0 001327_2011 0.120   0.141           0.160            0.751
 4 001327  2012     0 001327_2012 0.0946  0.106           0.129            0.734
 5 001327  2013     0 001327_2013 0.119   0.132           0.155            0.768
 6 001327  2014     0 001327_2014 0.154   0.181           0.200            0.771
 7 001327  2015     0 001327_2015 0.215   0.253           0.245            0.876
 8 001327  2016     0 001327_2016 0.258   0.281           0.303            0.853
 9 001382  2010     0 001382_2010 0.0642  5.01            0.0422           1.52 
10 001382  2011     0 001382_2011 0.00852 0.473           0.00544          1.57 
# ℹ 2,381 more rows
# ℹ 11 more variables: debt_to_equity &lt;dbl&gt;, debt_ratio &lt;dbl&gt;, PE_ratio &lt;dbl&gt;,
#   market_to_book &lt;dbl&gt;, operating_cash_flow_to_debt &lt;dbl&gt;,
#   free_cash_flow_to_sales &lt;dbl&gt;, book_value &lt;dbl&gt;, ebitda &lt;dbl&gt;,
#   ebitda_margin &lt;dbl&gt;, roic &lt;dbl&gt;, leverage &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>free_cash_flow_to_sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
-70.8481  -0.0439   0.0484  -1.3788   0.1446   0.6484     2026 </code></pre>
</div>
</div>
<p>Here we affect the value of the median for all Na</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>ebitda_margin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
-82.5545   0.0281   0.1286  -1.5030   0.2732   0.6737     2039 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>net_profit_margin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
-88.4300  -0.0645   0.0403  -1.7761   0.1177   0.5200     1937 </code></pre>
</div>
</div>
</section>
<section id="imputation" class="level4">
<h4 class="anchored" data-anchor-id="imputation">Imputation</h4>
<p><strong>MICE with Predictive Mean Matching (PMM)</strong> is a robust method for handling missing data. MICE iteratively imputes missing values by modeling each variable conditionally on others.</p>
<p><strong>PMM</strong> predicts missing values using regression and replaces them with observed values closest to the prediction, ensuring realistic imputations that respect the original data distribution.</p>
<p>With <code>m = 5</code>, multiple datasets are generated to account for imputation uncertainty, and <code>seed = 123</code> ensures reproducibility. This approach reduces bias, preserves variability, and produces reliable analyses by addressing missing data effectively.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  1   2  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  1   3  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  1   4  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  1   5  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  2   1  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  2   2  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  2   3  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  2   4  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  2   5  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  3   1  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  3   2  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  3   3  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  3   4  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  3   5  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  4   1  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  4   2  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  4   3  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  4   4  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  4   5  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  5   1  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  5   2  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  5   3  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  5   4  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage
  5   5  ROE  net_profit_margin  debt_to_equity  PE_ratio  market_to_book  operating_cash_flow_to_debt  free_cash_flow_to_sales  book_value  ebitda  ebitda_margin  roic  leverage</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Class: mids
Number of multiple imputations:  5 
Imputation methods:
                      gvkey                       fyear 
                         ""                          "" 
                          Y                          ID 
                         ""                          "" 
                        ROA                         ROE 
                         ""                       "pmm" 
          net_profit_margin              asset_turnover 
                      "pmm"                          "" 
             debt_to_equity                  debt_ratio 
                      "pmm"                          "" 
                   PE_ratio              market_to_book 
                      "pmm"                       "pmm" 
operating_cash_flow_to_debt     free_cash_flow_to_sales 
                      "pmm"                       "pmm" 
                 book_value                      ebitda 
                      "pmm"                       "pmm" 
              ebitda_margin                        roic 
                      "pmm"                       "pmm" 
                   leverage 
                      "pmm" 
PredictorMatrix:
      gvkey fyear Y ID ROA ROE net_profit_margin asset_turnover debt_to_equity
gvkey     0     1 1  0   1   1                 1              1              1
fyear     0     0 1  0   1   1                 1              1              1
Y         0     1 0  0   1   1                 1              1              1
ID        0     1 1  0   1   1                 1              1              1
ROA       0     1 1  0   0   1                 1              1              1
ROE       0     1 1  0   1   0                 1              1              1
      debt_ratio PE_ratio market_to_book operating_cash_flow_to_debt
gvkey          1        1              1                           1
fyear          1        1              1                           1
Y              1        1              1                           1
ID             1        1              1                           1
ROA            1        1              1                           1
ROE            1        1              1                           1
      free_cash_flow_to_sales book_value ebitda ebitda_margin roic leverage
gvkey                       1          1      1             1    1        1
fyear                       1          1      1             1    1        1
Y                           1          1      1             1    1        1
ID                          1          1      1             1    1        1
ROA                         1          1      1             1    1        1
ROE                         1          1      1             1    1        1
Number of logged events:  2 
  it im dep     meth   out
1  0  0     constant gvkey
2  0  0     constant    ID</code></pre>
</div>
</div>
</section>
</section>
<section id="descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h2>
<section id="target-variable" class="level4">
<h4 class="anchored" data-anchor-id="target-variable">Target Variable</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les gvkey ayant au moins une fois Y = 1</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>gvkey_with_Y1 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gvkey) <span class="sc">%&gt;%</span> <span class="co"># Grouper par gvkey</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">has_Y1 =</span> <span class="fu">any</span>(Y <span class="sc">==</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span> <span class="co"># Vérifier si Y = 1 existe pour chaque gvkey</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">proportion_Y1 =</span> <span class="fu">mean</span>(has_Y1)) <span class="co"># Calculer la proportion</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher la proportion</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gvkey_with_Y1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  proportion_Y1
          &lt;dbl&gt;
1        0.0274</code></pre>
</div>
</div>
<p>We have almost 3% of company that have bankrupted</p>
</section>
</section>
<section id="survival-analysis-hazard-model" class="level2">
<h2 class="anchored" data-anchor-id="survival-analysis-hazard-model">Survival analysis (Hazard Model)</h2>
<p><strong>Survival Analysis in Bankruptcy Scoring</strong></p>
<p>Survival analysis is a statistical approach to predict the time to an event, such as a company’s bankruptcy. The <strong>Cox Proportional Hazards Model</strong> is used to evaluate the relationship between financial ratios and the hazard of bankruptcy. This model estimates how variables like profitability (e.g., ROA, ROE), leverage (e.g., debt-to-equity, debt ratio), and efficiency (e.g., asset turnover) impact the likelihood of bankruptcy over time.</p>
<p>In the code, the model is fitted with financial variables as predictors and time-to-bankruptcy as the survival outcome. The results reveal the significant factors influencing the bankruptcy risk.</p>
<p>Create time and status variables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare survival data</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gvkey) <span class="sc">%&gt;%</span> <span class="co"># Group by firm identifier</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time =</span> fyear <span class="sc">-</span> <span class="fu">min</span>(fyear),  <span class="co"># Calculate time-to-event</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">status =</span> Y) <span class="sc">%&gt;%</span>            <span class="co"># Status (1 = bankruptcy, 0 = no event)</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Fit the Cox Proportional Hazards Model (all the variables except ones define below with values goes to infinity)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the Cox Proportional Hazards Model</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>cox_model <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>                     ROA <span class="sc">+</span> ROE <span class="sc">+</span> net_profit_margin <span class="sc">+</span> asset_turnover <span class="sc">+</span> </span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>                     debt_to_equity <span class="sc">+</span> debt_ratio <span class="sc">+</span> PE_ratio <span class="sc">+</span> </span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>                     market_to_book <span class="sc">+</span> operating_cash_flow_to_debt <span class="sc">+</span> </span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>                     free_cash_flow_to_sales <span class="sc">+</span> ebitda_margin <span class="sc">+</span> roic <span class="sc">+</span> leverage, </span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> df)</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a><span class="co"># View model summary</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, status) ~ ROA + ROE + net_profit_margin + 
    asset_turnover + debt_to_equity + debt_ratio + PE_ratio + 
    market_to_book + operating_cash_flow_to_debt + free_cash_flow_to_sales + 
    ebitda_margin + roic + leverage, data = df)

  n= 43919, number of events= 165 

                                 coef exp(coef)  se(coef)      z Pr(&gt;|z|)    
ROA                         -1.530601  0.216406  0.217222 -7.046 1.84e-12 ***
ROE                         -0.115096  0.891280  0.046795 -2.460  0.01391 *  
net_profit_margin            0.082700  1.086216  0.025601  3.230  0.00124 ** 
asset_turnover              -0.207946  0.812251  0.130914 -1.588  0.11219    
debt_to_equity              -0.014424  0.985679  0.015279 -0.944  0.34515    
debt_ratio                  -0.074866  0.927868  0.490412 -0.153  0.87867    
PE_ratio                    -0.003923  0.996085  0.001418 -2.766  0.00567 ** 
market_to_book              -0.003850  0.996157  0.011519 -0.334  0.73820    
operating_cash_flow_to_debt  0.143721  1.154562  0.149823  0.959  0.33742    
free_cash_flow_to_sales     -0.020977  0.979241  0.038674 -0.542  0.58753    
ebitda_margin               -0.063544  0.938433  0.031885 -1.993  0.04627 *  
roic                         0.429924  1.537140  0.151399  2.840  0.00452 ** 
leverage                     1.965214  7.136440  0.326827  6.013 1.82e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

                            exp(coef) exp(-coef) lower .95 upper .95
ROA                            0.2164     4.6210    0.1414    0.3313
ROE                            0.8913     1.1220    0.8132    0.9769
net_profit_margin              1.0862     0.9206    1.0331    1.1421
asset_turnover                 0.8123     1.2311    0.6284    1.0498
debt_to_equity                 0.9857     1.0145    0.9566    1.0156
debt_ratio                     0.9279     1.0777    0.3549    2.4262
PE_ratio                       0.9961     1.0039    0.9933    0.9989
market_to_book                 0.9962     1.0039    0.9739    1.0189
operating_cash_flow_to_debt    1.1546     0.8661    0.8608    1.5486
free_cash_flow_to_sales        0.9792     1.0212    0.9078    1.0564
ebitda_margin                  0.9384     1.0656    0.8816    0.9990
roic                           1.5371     0.6506    1.1425    2.0682
leverage                       7.1364     0.1401    3.7609   13.5418

Concordance= 0.824  (se = 0.025 )
Likelihood ratio test= 298.4  on 13 df,   p=&lt;2e-16
Wald test            = 459.9  on 13 df,   p=&lt;2e-16
Score (logrank) test = 681  on 13 df,   p=&lt;2e-16</code></pre>
</div>
</div>
<section id="model-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="model-evaluation">Model evaluation</h3>
<p>The C-index measures the model’s ability to rank survival times correctly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Concordance index</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>cox_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(cox_model)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>c_index <span class="ot">&lt;-</span> cox_summary<span class="sc">$</span>concordance[<span class="dv">1</span>]  <span class="co"># First element of concordance contains the C-index</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Concordance Index (C-Index):"</span>, c_index, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Concordance Index (C-Index): 0.8236046 </code></pre>
</div>
</div>
<p>risk scores (linear predictors) to use them for stratification or classification</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute risk scores</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>risk_scores <span class="ot">&lt;-</span> <span class="fu">predict</span>(cox_model, <span class="at">type =</span> <span class="st">"risk"</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add risk scores to the dataset</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">risk_score =</span> risk_scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we dichotomize the risk (e.g., high vs.&nbsp;low risk based on the median risk score), you can compute confusion matrices.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dichotomize risk scores: high risk (1) vs. low risk (0) based on the median</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fu">median</span>(risk_scores)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predicted_status =</span> <span class="fu">ifelse</span>(risk_score <span class="sc">&gt;</span> threshold, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create confusion matrix</span></span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'caret'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:survival':

    cluster</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>confusion <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(df<span class="sc">$</span>predicted_status), <span class="fu">as.factor</span>(df<span class="sc">$</span>status))</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction     0     1
         0 21943    17
         1 21811   148
                                          
               Accuracy : 0.503           
                 95% CI : (0.4983, 0.5077)
    No Information Rate : 0.9962          
    P-Value [Acc &gt; NIR] : 1               
                                          
                  Kappa : 0.006           
                                          
 Mcnemar's Test P-Value : &lt;2e-16          
                                          
            Sensitivity : 0.50151         
            Specificity : 0.89697         
         Pos Pred Value : 0.99923         
         Neg Pred Value : 0.00674         
             Prevalence : 0.99624         
         Detection Rate : 0.49962         
   Detection Prevalence : 0.50001         
      Balanced Accuracy : 0.69924         
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
</section>
</section>
<section id="logistic-model" class="level2">
<h2 class="anchored" data-anchor-id="logistic-model">Logistic Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gvkey) <span class="sc">%&gt;%</span> <span class="co"># Group by firm identifier</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time =</span> fyear <span class="sc">-</span> <span class="fu">min</span>(fyear),  <span class="co"># Calculate time-to-event</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">status =</span> Y) <span class="sc">%&gt;%</span>            <span class="co"># Status (1 = bankruptcy, 0 = no event)</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [43,919 × 21] (S3: tbl_df/tbl/data.frame)
 $ gvkey                      : chr [1:43919] "001004" "001004" "001004" "001004" ...
 $ fyear                      : int [1:43919] 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 ...
 $ Y                          : num [1:43919] 0 0 0 0 0 0 0 0 0 0 ...
 $ ID                         : chr [1:43919] "001004_2010" "001004_2011" "001004_2012" "001004_2013" ...
 $ ROA                        : num [1:43919] 0.04098 0.03084 0.02574 0.03314 0.00673 ...
 $ ROE                        : num [1:43919] 0.0835 0.0783 0.0599 0.0729 0.0121 ...
 $ net_profit_margin          : num [1:43919] 0.0393 0.0326 0.0254 0.0358 0.0064 ...
 $ asset_turnover             : num [1:43919] 1.042 0.945 1.014 0.925 1.052 ...
 $ debt_to_equity             : num [1:43919] 1.039 1.538 1.325 1.199 0.793 ...
 $ debt_ratio                 : num [1:43919] 0.51 0.606 0.57 0.545 0.442 ...
 $ PE_ratio                   : num [1:43919] 12.3 14.3 11.8 12.6 92.7 ...
 $ market_to_book             : num [1:43919] 1.03 1.118 0.704 0.92 1.119 ...
 $ operating_cash_flow_to_debt: num [1:43919] 0.125 0.0709 0.1338 0.1166 -0.0642 ...
 $ free_cash_flow_to_sales    : num [1:43919] -0.00917 0.00145 0.05782 0.05568 -0.05601 ...
 $ book_value                 : num [1:43919] 770 1215 1080 1038 565 ...
 $ ebitda                     : num [1:43919] 196.3 222.7 245.2 256 83.7 ...
 $ ebitda_margin              : num [1:43919] 0.1105 0.1073 0.1131 0.1258 0.0525 ...
 $ roic                       : num [1:43919] 0.1534 0.1344 0.1507 0.1567 0.0838 ...
 $ leverage                   : num [1:43919] 0.347 0.478 0.435 0.388 0.154 ...
 $ time                       : int [1:43919] 0 1 2 3 4 5 6 7 8 9 ...
 $ status                     : num [1:43919] 0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a formula for the logistic regression</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude non-numeric predictors like gvkey, ID, and time</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>predictors <span class="ot">&lt;-</span> <span class="fu">names</span>(df)[<span class="sc">!</span><span class="fu">names</span>(df) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"gvkey"</span>, <span class="st">"fyear"</span>, <span class="st">"ID"</span>, <span class="st">"Y"</span>, <span class="st">"status"</span>)]</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct the formula dynamically</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>formula <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"Y ~"</span>, <span class="fu">paste</span>(predictors, <span class="at">collapse =</span> <span class="st">" + "</span>)))</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the logistic regression model</span></span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>logistic_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(formula, <span class="at">data =</span> df, <span class="at">family =</span> binomial)</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the model</span></span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = formula, family = binomial, data = df)

Coefficients:
                              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                 -6.511e+00  2.502e-01 -26.027  &lt; 2e-16 ***
ROA                         -1.499e+00  2.540e-01  -5.903 3.57e-09 ***
ROE                         -1.369e-01  5.002e-02  -2.738  0.00619 ** 
net_profit_margin            7.441e-02  2.343e-02   3.176  0.00149 ** 
asset_turnover              -2.260e-01  1.264e-01  -1.789  0.07363 .  
debt_to_equity              -1.510e-02  1.437e-02  -1.051  0.29325    
debt_ratio                  -1.018e-01  4.365e-01  -0.233  0.81561    
PE_ratio                    -2.098e-03  1.432e-03  -1.465  0.14285    
market_to_book              -7.010e-03  1.122e-02  -0.624  0.53230    
operating_cash_flow_to_debt  2.871e-01  1.588e-01   1.808  0.07055 .  
free_cash_flow_to_sales     -1.496e-02  3.550e-02  -0.422  0.67337    
book_value                   1.749e-05  1.402e-05   1.248  0.21202    
ebitda                      -1.585e-03  3.659e-04  -4.332 1.48e-05 ***
ebitda_margin               -5.592e-02  2.883e-02  -1.940  0.05244 .  
roic                         7.483e-01  1.678e-01   4.459 8.24e-06 ***
leverage                     2.231e+00  2.837e-01   7.864 3.72e-15 ***
time                         3.147e-03  2.159e-02   0.146  0.88411    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2172.2  on 43918  degrees of freedom
Residual deviance: 1815.7  on 43902  degrees of freedom
AIC: 1849.7

Number of Fisher Scoring iterations: 11</code></pre>
</div>
</div>
<p>The logistic regression model evaluates the relationship between financial variables and the probability of bankruptcy. Key results:</p>
<ul>
<li><p><strong>Significant Predictors</strong>:</p>
<ul>
<li><strong>ROA</strong>: Negative coefficient (-1.499, <em>p</em> &lt; 0.001) indicates higher ROA reduces bankruptcy risk.</li>
<li><strong>ROE</strong>: Negative coefficient (-0.137, <em>p</em> &lt; 0.01) suggests higher ROE lowers risk.</li>
<li><strong>Net Profit Margin</strong>: Positive coefficient (0.074, <em>p</em> &lt; 0.01) suggests higher margins increase bankruptcy likelihood, potentially due to overstated profits.</li>
<li><strong>EBITDA</strong>: Negative coefficient (-0.0016, <em>p</em> &lt; 0.001) implies higher EBITDA reduces risk.</li>
<li><strong>ROIC</strong>: Positive coefficient (0.748, <em>p</em> &lt; 0.001) indicates higher ROIC increases risk, possibly signaling aggressive reinvestment strategies.</li>
<li><strong>Leverage</strong>: Strong positive effect (2.231, <em>p</em> &lt; 0.001) highlights higher leverage as a key bankruptcy driver.</li>
</ul></li>
<li><p><strong>Non-Significant Predictors</strong>: Variables like debt-to-equity, debt ratio, and market-to-book ratio showed no significant effect (<em>p</em> &gt; 0.1).</p></li>
<li><p><strong>Model Fit</strong>:</p>
<ul>
<li>Residual deviance decreased substantially (2172.2 to 1815.7), and the AIC is 1849.7, indicating a good fit.</li>
</ul></li>
</ul>
<p>This model identifies leverage and profitability measures as critical indicators of bankruptcy risk, providing actionable insights for financial analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="prediction-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="prediction-evaluation">Prediction Evaluation</h3>
<p><strong>Train-Test split</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Train-test split</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># Set seed for reproducibility</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>train_index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(data<span class="sc">$</span>Y, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)  <span class="co"># 70% training data</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> data[train_index, ]</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> data[<span class="sc">-</span>train_index, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Train the model</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Train the Logistic Regression Model</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude non-numeric predictors like gvkey, ID, and time</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>predictors <span class="ot">&lt;-</span> <span class="fu">names</span>(data)[<span class="sc">!</span><span class="fu">names</span>(data) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"gvkey"</span>, <span class="st">"fyear"</span>, <span class="st">"ID"</span>, <span class="st">"Y"</span>, <span class="st">"status"</span>)]</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct the formula dynamically</span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>formula <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"Y ~"</span>, <span class="fu">paste</span>(predictors, <span class="at">collapse =</span> <span class="st">" + "</span>)))</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the logistic regression model</span></span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a>logistic_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(formula, <span class="at">data =</span> data, <span class="at">family =</span> binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Summarize the Model</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Summarize the Model</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = formula, family = binomial, data = data)

Coefficients:
                              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                 -6.511e+00  2.502e-01 -26.027  &lt; 2e-16 ***
ROA                         -1.499e+00  2.540e-01  -5.903 3.57e-09 ***
ROE                         -1.369e-01  5.002e-02  -2.738  0.00619 ** 
net_profit_margin            7.441e-02  2.343e-02   3.176  0.00149 ** 
asset_turnover              -2.260e-01  1.264e-01  -1.789  0.07363 .  
debt_to_equity              -1.510e-02  1.437e-02  -1.051  0.29325    
debt_ratio                  -1.018e-01  4.365e-01  -0.233  0.81561    
PE_ratio                    -2.098e-03  1.432e-03  -1.465  0.14285    
market_to_book              -7.010e-03  1.122e-02  -0.624  0.53230    
operating_cash_flow_to_debt  2.871e-01  1.588e-01   1.808  0.07055 .  
free_cash_flow_to_sales     -1.496e-02  3.550e-02  -0.422  0.67337    
book_value                   1.749e-05  1.402e-05   1.248  0.21202    
ebitda                      -1.585e-03  3.659e-04  -4.332 1.48e-05 ***
ebitda_margin               -5.592e-02  2.883e-02  -1.940  0.05244 .  
roic                         7.483e-01  1.678e-01   4.459 8.24e-06 ***
leverage                     2.231e+00  2.837e-01   7.864 3.72e-15 ***
time                         3.147e-03  2.159e-02   0.146  0.88411    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2172.2  on 43918  degrees of freedom
Residual deviance: 1815.7  on 43902  degrees of freedom
AIC: 1849.7

Number of Fisher Scoring iterations: 11</code></pre>
</div>
</div>
<p><strong>Evaluate the model on test data</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Evaluate the Model on Test Data</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict probabilities for the test set</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> test_data <span class="sc">%&gt;%</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predicted_prob =</span> <span class="fu">predict</span>(logistic_model, <span class="at">newdata =</span> ., <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create predictions based on a cutoff (e.g., 0.5)</span></span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> test_data <span class="sc">%&gt;%</span></span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predicted_class =</span> <span class="fu">ifelse</span>(predicted_prob <span class="sc">&gt;</span> <span class="fl">0.3</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Model Evaluation Metrics</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion Matrix</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>confusion_matrix <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Predicted =</span> test_data<span class="sc">$</span>predicted_class, <span class="at">Actual =</span> test_data<span class="sc">$</span>Y)</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Confusion Matrix:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confusion Matrix:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusion_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted     0     1
        0 13126    46
        1     2     1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(confusion_matrix)) <span class="sc">/</span> <span class="fu">sum</span>(confusion_matrix)</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Accuracy:"</span>, <span class="fu">round</span>(accuracy, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Accuracy: 0.9964"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Precision (for the positive class)</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>precision <span class="ot">&lt;-</span> confusion_matrix[<span class="dv">2</span>, <span class="dv">2</span>] <span class="sc">/</span> <span class="fu">sum</span>(confusion_matrix[<span class="dv">2</span>, ])</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Precision:"</span>, <span class="fu">round</span>(precision, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Precision: 0.3333"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recall (Sensitivity or True Positive Rate)</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>recall <span class="ot">&lt;-</span> confusion_matrix[<span class="dv">2</span>, <span class="dv">2</span>] <span class="sc">/</span> <span class="fu">sum</span>(confusion_matrix[, <span class="dv">2</span>])</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Recall (Sensitivity):"</span>, <span class="fu">round</span>(recall, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Recall (Sensitivity): 0.0213"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specificity (True Negative Rate)</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>specificity <span class="ot">&lt;-</span> confusion_matrix[<span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">/</span> <span class="fu">sum</span>(confusion_matrix[, <span class="dv">1</span>])</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Specificity:"</span>, <span class="fu">round</span>(specificity, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Specificity: 0.9998"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># F1 Score</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>f1_score <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> ((precision <span class="sc">*</span> recall) <span class="sc">/</span> (precision <span class="sc">+</span> recall))</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"F1 Score:"</span>, <span class="fu">round</span>(f1_score, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F1 Score: 0.04"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ROC Curve and AUC</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(test_data<span class="sc">$</span>Y, test_data<span class="sc">$</span>predicted_prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"AUC:"</span>, <span class="fu">round</span>(<span class="fu">auc</span>(roc_curve), <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AUC: 0.7859"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">main =</span> <span class="st">"ROC Curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practical1_task2_3_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(roc_curve)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.7859</code></pre>
</div>
</div>
<p><strong>Cross Validation to choose the threshold</strong></p>
<p>This code performs an analysis to determine the optimal classification threshold for a binary classification model, using cross-validation to evaluate performance across multiple metrics. Here’s a breakdown of the process:</p>
<ol type="1">
<li><strong>Define Thresholds</strong>:
<ul>
<li>A sequence of thresholds (0 to 1 in steps of 0.01) is defined to evaluate model predictions.</li>
</ul></li>
<li><strong>Metrics Calculation</strong>:
<ul>
<li>For each threshold, predicted probabilities (<code>predicted_prob</code>) are converted into binary predictions (<code>predicted_class</code>) based on whether they exceed the threshold.</li>
<li>A confusion matrix is generated for the predictions to calculate key metrics:
<ul>
<li><strong>Accuracy</strong>: Overall correctness.</li>
<li><strong>Precision</strong>: Correct positive predictions among all positive predictions.</li>
<li><strong>Recall</strong>: Correct positive predictions among all actual positives.</li>
<li><strong>F1 Score</strong>: Harmonic mean of precision and recall.</li>
</ul></li>
</ul></li>
<li><strong>Cross-Validation Results</strong>:
<ul>
<li>The calculated metrics are stored in a dataframe (<code>cv_results</code>) for all thresholds.</li>
</ul></li>
<li><strong>Optimal Threshold</strong>:
<ul>
<li>The threshold maximizing a chosen metric (e.g., F1 Score) is identified and printed as the optimal threshold.</li>
</ul></li>
<li><strong>Visualization</strong>:
<ul>
<li>Metrics are plotted against thresholds using a line plot, showing how each metric varies with the threshold.</li>
</ul></li>
</ol>
<p>This approach ensures the model’s classification threshold is tuned to balance the trade-offs between precision, recall, and other performance measures, aligning with the specific objectives of the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a sequence of thresholds to test</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>thresholds <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize a dataframe to store results</span></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>cv_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">threshold =</span> thresholds, <span class="at">accuracy =</span> <span class="cn">NA</span>, <span class="at">precision =</span> <span class="cn">NA</span>, <span class="at">recall =</span> <span class="cn">NA</span>, <span class="at">f1_score =</span> <span class="cn">NA</span>)</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform cross-validation for each threshold</span></span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(thresholds)) {</span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a>  threshold <span class="ot">&lt;-</span> thresholds[i]</span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb119-11"><a href="#cb119-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create predictions based on the current threshold</span></span>
<span id="cb119-12"><a href="#cb119-12" aria-hidden="true" tabindex="-1"></a>  test_data <span class="ot">&lt;-</span> test_data <span class="sc">%&gt;%</span></span>
<span id="cb119-13"><a href="#cb119-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predicted_class =</span> <span class="fu">ifelse</span>(predicted_prob <span class="sc">&gt;</span> threshold, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb119-14"><a href="#cb119-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb119-15"><a href="#cb119-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Confusion Matrix</span></span>
<span id="cb119-16"><a href="#cb119-16" aria-hidden="true" tabindex="-1"></a>  confusion_matrix <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Predicted =</span> test_data<span class="sc">$</span>predicted_class, <span class="at">Actual =</span> test_data<span class="sc">$</span>Y)</span>
<span id="cb119-17"><a href="#cb119-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb119-18"><a href="#cb119-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Handle cases where the confusion matrix dimensions are insufficient</span></span>
<span id="cb119-19"><a href="#cb119-19" aria-hidden="true" tabindex="-1"></a>  tp <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="st">"1"</span> <span class="sc">%in%</span> <span class="fu">rownames</span>(confusion_matrix) <span class="sc">&amp;</span> <span class="st">"1"</span> <span class="sc">%in%</span> <span class="fu">colnames</span>(confusion_matrix), confusion_matrix[<span class="st">"1"</span>, <span class="st">"1"</span>], <span class="dv">0</span>)</span>
<span id="cb119-20"><a href="#cb119-20" aria-hidden="true" tabindex="-1"></a>  fp <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="st">"1"</span> <span class="sc">%in%</span> <span class="fu">rownames</span>(confusion_matrix) <span class="sc">&amp;</span> <span class="st">"0"</span> <span class="sc">%in%</span> <span class="fu">colnames</span>(confusion_matrix), confusion_matrix[<span class="st">"1"</span>, <span class="st">"0"</span>], <span class="dv">0</span>)</span>
<span id="cb119-21"><a href="#cb119-21" aria-hidden="true" tabindex="-1"></a>  fn <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="st">"0"</span> <span class="sc">%in%</span> <span class="fu">rownames</span>(confusion_matrix) <span class="sc">&amp;</span> <span class="st">"1"</span> <span class="sc">%in%</span> <span class="fu">colnames</span>(confusion_matrix), confusion_matrix[<span class="st">"0"</span>, <span class="st">"1"</span>], <span class="dv">0</span>)</span>
<span id="cb119-22"><a href="#cb119-22" aria-hidden="true" tabindex="-1"></a>  tn <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="st">"0"</span> <span class="sc">%in%</span> <span class="fu">rownames</span>(confusion_matrix) <span class="sc">&amp;</span> <span class="st">"0"</span> <span class="sc">%in%</span> <span class="fu">colnames</span>(confusion_matrix), confusion_matrix[<span class="st">"0"</span>, <span class="st">"0"</span>], <span class="dv">0</span>)</span>
<span id="cb119-23"><a href="#cb119-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb119-24"><a href="#cb119-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate metrics</span></span>
<span id="cb119-25"><a href="#cb119-25" aria-hidden="true" tabindex="-1"></a>  accuracy <span class="ot">&lt;-</span> (tp <span class="sc">+</span> tn) <span class="sc">/</span> <span class="fu">sum</span>(confusion_matrix)</span>
<span id="cb119-26"><a href="#cb119-26" aria-hidden="true" tabindex="-1"></a>  precision <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(tp <span class="sc">+</span> fp <span class="sc">&gt;</span> <span class="dv">0</span>, tp <span class="sc">/</span> (tp <span class="sc">+</span> fp), <span class="cn">NA</span>)</span>
<span id="cb119-27"><a href="#cb119-27" aria-hidden="true" tabindex="-1"></a>  recall <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(tp <span class="sc">+</span> fn <span class="sc">&gt;</span> <span class="dv">0</span>, tp <span class="sc">/</span> (tp <span class="sc">+</span> fn), <span class="cn">NA</span>)</span>
<span id="cb119-28"><a href="#cb119-28" aria-hidden="true" tabindex="-1"></a>  f1_score <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(precision) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(recall) <span class="sc">&amp;</span> (precision <span class="sc">+</span> recall <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="dv">2</span> <span class="sc">*</span> ((precision <span class="sc">*</span> recall) <span class="sc">/</span> (precision <span class="sc">+</span> recall)), <span class="cn">NA</span>)</span>
<span id="cb119-29"><a href="#cb119-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb119-30"><a href="#cb119-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Store metrics in cv_results</span></span>
<span id="cb119-31"><a href="#cb119-31" aria-hidden="true" tabindex="-1"></a>  cv_results[i, ] <span class="ot">&lt;-</span> <span class="fu">c</span>(threshold, accuracy, precision, recall, f1_score)</span>
<span id="cb119-32"><a href="#cb119-32" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb119-33"><a href="#cb119-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-34"><a href="#cb119-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the optimal threshold based on a specific metric (e.g.,recall)</span></span>
<span id="cb119-35"><a href="#cb119-35" aria-hidden="true" tabindex="-1"></a>optimal_threshold <span class="ot">&lt;-</span> cv_results <span class="sc">%&gt;%</span> <span class="fu">filter</span>(f1_score <span class="sc">==</span> <span class="fu">max</span>(f1_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb119-36"><a href="#cb119-36" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(optimal_threshold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  threshold  accuracy  precision    recall  f1_score
1      0.06 0.9896774 0.07619048 0.1702128 0.1052632</code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot metrics against thresholds</span></span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>cv_results_long <span class="ot">&lt;-</span> cv_results <span class="sc">%&gt;%</span></span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(accuracy, precision, recall, f1_score), <span class="at">names_to =</span> <span class="st">"metric"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>)</span>
<span id="cb121-4"><a href="#cb121-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-5"><a href="#cb121-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cv_results_long, <span class="fu">aes</span>(<span class="at">x =</span> threshold, <span class="at">y =</span> value, <span class="at">color =</span> metric)) <span class="sc">+</span></span>
<span id="cb121-6"><a href="#cb121-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb121-7"><a href="#cb121-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Metrics vs Threshold"</span>, <span class="at">x =</span> <span class="st">"Threshold"</span>, <span class="at">y =</span> <span class="st">"Metric Value"</span>) <span class="sc">+</span></span>
<span id="cb121-8"><a href="#cb121-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 106 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practical1_task2_3_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the optimal threshold</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>optimal_threshold_value <span class="ot">&lt;-</span> optimal_threshold<span class="sc">$</span>threshold[<span class="dv">1</span>]</span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create predictions based on the optimal threshold</span></span>
<span id="cb123-5"><a href="#cb123-5" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> test_data <span class="sc">%&gt;%</span></span>
<span id="cb123-6"><a href="#cb123-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predicted_class =</span> <span class="fu">ifelse</span>(predicted_prob <span class="sc">&gt;</span> optimal_threshold_value, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb123-7"><a href="#cb123-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-8"><a href="#cb123-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the confusion matrix</span></span>
<span id="cb123-9"><a href="#cb123-9" aria-hidden="true" tabindex="-1"></a>confusion_matrix_optimal <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Predicted =</span> test_data<span class="sc">$</span>predicted_class, <span class="at">Actual =</span> test_data<span class="sc">$</span>Y)</span>
<span id="cb123-10"><a href="#cb123-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-11"><a href="#cb123-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the confusion matrix</span></span>
<span id="cb123-12"><a href="#cb123-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Confusion Matrix at Optimal Threshold:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Confusion Matrix at Optimal Threshold:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusion_matrix_optimal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted     0     1
        0 13031    39
        1    97     8</code></pre>
</div>
</div>
</section>
</section>
<section id="time-series-cross-validation" class="level2">
<h2 class="anchored" data-anchor-id="time-series-cross-validation"><strong>Time Series Cross-Validation</strong></h2>
<p>This code implements a <strong>Time Series Cross-Validation (Walk Forward Scheme)</strong> to evaluate the performance of a logistic regression model for predicting a bankruptcy. The process respects the temporal structure of the data to avoid data leakage by ensuring that future observations are not used for training.</p>
<p><strong>Steps:</strong></p>
<ol type="1">
<li><strong>Prepare and Sort Data</strong>:
<ul>
<li>The dataset is ordered by firm identifier (<code>gvkey</code>) and year (<code>fyear</code>) to preserve the chronological order.</li>
</ul></li>
<li><strong>Define Cross-Validation Splits</strong>:
<ul>
<li>A custom function creates training and testing indices for a walk-forward validation approach, splitting the data into 5 folds.</li>
</ul></li>
<li><strong>Model Training and Testing</strong>:
<ul>
<li>For each fold:
<ul>
<li>The model is trained on past data and tested on future data within the defined fold.</li>
<li>Logistic regression is used with financial variables as predictors.</li>
</ul></li>
</ul></li>
<li><strong>Performance Evaluation</strong>:
<ul>
<li>Predictions are evaluated using metrics like accuracy and Area Under the ROC Curve (AUC) to measure classification performance.</li>
<li>Confusion matrices and ROC curves provide additional insights into the model’s predictive ability.</li>
</ul></li>
</ol>
<p>This approach ensures robust and time-consistent model validation, simulating real-world scenarios where only past data is available to predict future outcomes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Prepare data</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Sort data by firm (gvkey) and year (fyear) to respect temporal structure</span></span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(gvkey, fyear)</span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Define Time Series Cross-Validation (Walk Forward Scheme)</span></span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create custom indices for training and testing</span></span>
<span id="cb127-7"><a href="#cb127-7" aria-hidden="true" tabindex="-1"></a>time_series_cv <span class="ot">&lt;-</span> <span class="cf">function</span>(data, n_splits) {</span>
<span id="cb127-8"><a href="#cb127-8" aria-hidden="true" tabindex="-1"></a>  indices <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb127-9"><a href="#cb127-9" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data)</span>
<span id="cb127-10"><a href="#cb127-10" aria-hidden="true" tabindex="-1"></a>  split_size <span class="ot">&lt;-</span> <span class="fu">floor</span>(n <span class="sc">/</span> (n_splits <span class="sc">+</span> <span class="dv">1</span>))  <span class="co"># Calculate split size</span></span>
<span id="cb127-11"><a href="#cb127-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb127-12"><a href="#cb127-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_splits) {</span>
<span id="cb127-13"><a href="#cb127-13" aria-hidden="true" tabindex="-1"></a>    train_end <span class="ot">&lt;-</span> split_size <span class="sc">*</span> i  <span class="co"># End index for training</span></span>
<span id="cb127-14"><a href="#cb127-14" aria-hidden="true" tabindex="-1"></a>    test_start <span class="ot">&lt;-</span> train_end <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb127-15"><a href="#cb127-15" aria-hidden="true" tabindex="-1"></a>    test_end <span class="ot">&lt;-</span> test_start <span class="sc">+</span> split_size <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb127-16"><a href="#cb127-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb127-17"><a href="#cb127-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (test_end <span class="sc">&gt;</span> n) <span class="cf">break</span>  <span class="co"># Ensure test indices stay within range</span></span>
<span id="cb127-18"><a href="#cb127-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb127-19"><a href="#cb127-19" aria-hidden="true" tabindex="-1"></a>    train_indices <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, train_end)</span>
<span id="cb127-20"><a href="#cb127-20" aria-hidden="true" tabindex="-1"></a>    test_indices <span class="ot">&lt;-</span> <span class="fu">seq</span>(test_start, test_end)</span>
<span id="cb127-21"><a href="#cb127-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb127-22"><a href="#cb127-22" aria-hidden="true" tabindex="-1"></a>    indices[[i]] <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">train =</span> train_indices, <span class="at">test =</span> test_indices)</span>
<span id="cb127-23"><a href="#cb127-23" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb127-24"><a href="#cb127-24" aria-hidden="true" tabindex="-1"></a>  indices</span>
<span id="cb127-25"><a href="#cb127-25" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create 5 splits for time series CV</span></span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>n_splits <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>cv_indices <span class="ot">&lt;-</span> <span class="fu">time_series_cv</span>(data, n_splits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Perform Walk Forward Validation</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(cv_indices)) {</span>
<span id="cb129-5"><a href="#cb129-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get train and test data</span></span>
<span id="cb129-6"><a href="#cb129-6" aria-hidden="true" tabindex="-1"></a>  train_data <span class="ot">&lt;-</span> data[cv_indices[[i]]<span class="sc">$</span>train, ]</span>
<span id="cb129-7"><a href="#cb129-7" aria-hidden="true" tabindex="-1"></a>  test_data <span class="ot">&lt;-</span> data[cv_indices[[i]]<span class="sc">$</span>test, ]</span>
<span id="cb129-8"><a href="#cb129-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb129-9"><a href="#cb129-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Fit logistic regression model on training data</span></span>
<span id="cb129-10"><a href="#cb129-10" aria-hidden="true" tabindex="-1"></a>  logistic_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb129-11"><a href="#cb129-11" aria-hidden="true" tabindex="-1"></a>    Y <span class="sc">~</span> ROA <span class="sc">+</span> ROE <span class="sc">+</span> net_profit_margin <span class="sc">+</span> asset_turnover <span class="sc">+</span> </span>
<span id="cb129-12"><a href="#cb129-12" aria-hidden="true" tabindex="-1"></a>       debt_to_equity <span class="sc">+</span> debt_ratio <span class="sc">+</span> PE_ratio <span class="sc">+</span> </span>
<span id="cb129-13"><a href="#cb129-13" aria-hidden="true" tabindex="-1"></a>       market_to_book <span class="sc">+</span> operating_cash_flow_to_debt <span class="sc">+</span> </span>
<span id="cb129-14"><a href="#cb129-14" aria-hidden="true" tabindex="-1"></a>       free_cash_flow_to_sales <span class="sc">+</span> ebitda_margin <span class="sc">+</span> roic <span class="sc">+</span> leverage, </span>
<span id="cb129-15"><a href="#cb129-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb129-16"><a href="#cb129-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> train_data</span>
<span id="cb129-17"><a href="#cb129-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb129-18"><a href="#cb129-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb129-19"><a href="#cb129-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Predict probabilities on test data</span></span>
<span id="cb129-20"><a href="#cb129-20" aria-hidden="true" tabindex="-1"></a>  test_data <span class="ot">&lt;-</span> test_data <span class="sc">%&gt;%</span></span>
<span id="cb129-21"><a href="#cb129-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">predicted_prob =</span> <span class="fu">predict</span>(logistic_model, <span class="at">newdata =</span> ., <span class="at">type =</span> <span class="st">"response"</span>),</span>
<span id="cb129-22"><a href="#cb129-22" aria-hidden="true" tabindex="-1"></a>           <span class="at">predicted_class =</span> <span class="fu">ifelse</span>(predicted_prob <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb129-23"><a href="#cb129-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb129-24"><a href="#cb129-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Evaluate model performance</span></span>
<span id="cb129-25"><a href="#cb129-25" aria-hidden="true" tabindex="-1"></a>  confusion_matrix <span class="ot">&lt;-</span> <span class="fu">table</span>(test_data<span class="sc">$</span>predicted_class, test_data<span class="sc">$</span>Y)</span>
<span id="cb129-26"><a href="#cb129-26" aria-hidden="true" tabindex="-1"></a>  accuracy <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(confusion_matrix)) <span class="sc">/</span> <span class="fu">sum</span>(confusion_matrix)</span>
<span id="cb129-27"><a href="#cb129-27" aria-hidden="true" tabindex="-1"></a>  roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(test_data<span class="sc">$</span>Y, test_data<span class="sc">$</span>predicted_prob)</span>
<span id="cb129-28"><a href="#cb129-28" aria-hidden="true" tabindex="-1"></a>  auc <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_curve)</span>
<span id="cb129-29"><a href="#cb129-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb129-30"><a href="#cb129-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Store results</span></span>
<span id="cb129-31"><a href="#cb129-31" aria-hidden="true" tabindex="-1"></a>  results[[i]] <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb129-32"><a href="#cb129-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">fold =</span> i,</span>
<span id="cb129-33"><a href="#cb129-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">accuracy =</span> accuracy,</span>
<span id="cb129-34"><a href="#cb129-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">auc =</span> auc,</span>
<span id="cb129-35"><a href="#cb129-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">confusion_matrix =</span> confusion_matrix,</span>
<span id="cb129-36"><a href="#cb129-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">roc_curve =</span> roc_curve</span>
<span id="cb129-37"><a href="#cb129-37" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb129-38"><a href="#cb129-38" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Summarize Results</span></span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>accuracy_list <span class="ot">&lt;-</span> <span class="fu">sapply</span>(results, <span class="cf">function</span>(x) x<span class="sc">$</span>accuracy)</span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a>auc_list <span class="ot">&lt;-</span> <span class="fu">sapply</span>(results, <span class="cf">function</span>(x) x<span class="sc">$</span>auc)</span>
<span id="cb140-4"><a href="#cb140-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-5"><a href="#cb140-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Walk Forward Validation Results:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Walk Forward Validation Results:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Average Accuracy:"</span>, <span class="fu">round</span>(<span class="fu">mean</span>(accuracy_list), <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average Accuracy: 0.9957 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Average AUC:"</span>, <span class="fu">round</span>(<span class="fu">mean</span>(auc_list), <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average AUC: 0.7879 </code></pre>
</div>
</div>
<p><strong>Walk Forward Validation Results Interpretation</strong></p>
<p>The model achieved an <strong>average accuracy of 99.57%</strong>, indicating that it correctly classified nearly all observations in the test sets. However, the <strong>average AUC of 0.7879</strong> suggests moderate discriminatory power, meaning the model performs reasonably well in distinguishing between the two classes but leaves room for improvement.</p>
<p>This discrepancy between accuracy and AUC highlights that while the model predicts the majority class well, it might struggle with imbalanced data or correctly classifying the minority class.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the last ROC curve as an example</span></span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(results[[n_splits]]<span class="sc">$</span>roc_curve, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">main =</span> <span class="st">"ROC Curve for Last Fold"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practical1_task2_3_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>